server:
  port: 9001
  servlet:
   context-path: /ljw
   session:
     timeout: PT2H
spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://47.108.30.112:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: ljw
  password: 'll99801404'
  hikari:
   minimum-idle: 3
   maximum-pool-size: 10
   max-lifetime: 30000
   connection-test-query: SELECT 1
 http:
  encoding:
   force-request: true
   enabled: true
   charset: UTF-8
 mvc:
  static-path-pattern: /**
 thymeleaf:
  mode: HTML5
  encoding: UTF-8
  cache: false
 redis:
  host: localhost
  port: 6379
  password: 123456
mybatis:
  mapper-locations: classpath:com/ljw/springboot/thymeleaf/mapping/*.xml
  type-aliases-package: com.ljw.springboot.thymeleaf.mapper
  # spring boot集成mybatis的方式打印sql
  #configuration:
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# pagehelper
pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count=countSql
nginxport: http://47.108.30.112