server:
  port: 80
  servlet:
    context-path: /ljw
spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: '123456'
 http:
  encoding:
   force-request: true
   enabled: true
   charset: UTF-8
 mvc:
  static-path-pattern: /**
 thymeleaf:
  mode: HTML5
  encoding: UTF-8
  cache: false
 redis:
  host: localhost
  port: 6379
  password: 123456
mybatis:
  mapper-locations: classpath:com/ljw/springboot/thymeleaf/mapping/*.xml
  type-aliases-package: com.ljw.springboot.thymeleaf.mapper
